# Menu
menu:
  首页: /
  归档: /archives
  # 相册: /gallery/index.html
  相册: /album
  收藏: /collect/index.html
  关于: /about
rss: /atom.xml


# Miscellaneous
favicon: /images/shark.ico
brand: /images/shark.svg

# Ocean 主页视频
# 多种格式的视频用于支持不同的浏览器，这里只需要配置好路径，前提是我把视频相关文件统一目录存放。
ocean:
  overlay: true  # 可选，false 则 Ocean 视频下方的笔触式遮盖不显示
  path: /images/ocean/  # 视频统一存放路径，格式 mp4/ogg/webm
  brand: /images/shark.svg  # 可选，一个小 Logo

# 内容
excerpt_link: 阅读全文...

# MIIT ICP/IP/DOMAIN
beian:
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'